apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-buildpack-demo-2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/midawson-tenant/rhtap-buildpack-demo-2/rhtap-buildpack-demo-2@sha256:6f6ef4dcde36804065a2f9e852017e7b94b61722fd7a095ca2d71088cc069218
        name: my-nodejs
        resources: {}
status: {}
