apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-buildpack-demo-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-buildpack-demo-2
    app.kubernetes.io/part-of: rhtap-buildpack-demo-2
  name: rhtap-buildpack-demo-2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: rhtap-buildpack-demo-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: rhtap-buildpack-demo-2
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/midawson-tenant/rhtap-buildpack-demo-2/rhtap-buildpack-demo-2@sha256:6f6ef4dcde36804065a2f9e852017e7b94b61722fd7a095ca2d71088cc069218
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
